export const queues = {
  TEMPORAL_QUEUE_LIGHT: 'TEMPORAL_QUEUE_LIGHT',
  TEMPORAL_QUEUE_HEAVY: 'TEMPORAL_QUEUE_HEAVY',
  TEMPORAL_QUEUE_PYTHON_LIGHT: 'TEMPORAL_QUEUE_PYTHON_LIGHT',
  TEMPORAL_QUEUE_PYTHON_HEAVY: 'TEMPORAL_QUEUE_PYTHON_HEAVY',
  HIVEMIND_AGENT_QUEUE: 'HIVEMIND_AGENT_QUEUE',
};
